packages:
  - 'packages/*'
verifyDepsBeforeRun: false
autoInstallPeers: false
overrides:
  'eslint-plugin-tsdoc>@typescript-eslint/utils': 8.67.0
  'nanoid@<3.3.18': 3.3.18
allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': false
  '@swc/core': true
  better-sqlite3: false
  bufferutil: false
  canvas: false
  core-js: false
  core-js-pure: false
  edgedriver: false
  esbuild: true
  fibers: false
  geckodriver: false
  kerberos: false
  libpq: false
  msgpackr-extract: false
  msw: false
  node-sass: false
  prisma: false
  sqlite3: false
  unrs-resolver: true
  utf-8-validate: false
